--- 
- hosts: 172.31.86.8
  become: yes
  tasks:
  - name: install tree
    apt:
     name: tree
     state: present

  - name: install wget
    apt:
     name: wgettt
     state: present   
    ignore_errors: yes 

  - name: install tree
    apt:
      name: tree
      state: present