---
- hosts: 172.31.86.8
  become: yes
  tasks: 
  -  include_tasks: myfile.yml

  - name: copy file from master to node
    copy:
     src: my2ndfile.txt
     dest: /home/ubuntu/my2ndfile.txt

  - name: install apache2
    apt:
      name: apache2
      state: present  

  - name: copy dynamic file into node side
    template: 
        src: myindex.j2
        dest: /var/www/html/index.html    

  -  name: download remote
     get_url:
      url: https://mybucket-12-08.s3.amazonaws.com/538-2021-637720625240871340.pdf
      dest: /home/ubuntu/538-2021-637720625240871340.pdf
      force_basic_auth: yes    